# Generated by Django 4.2.4 on 2023-09-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_like_count_delete_likecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_count',
            new_name='num_likes',
        ),
    ]
